language: java


services:
  - docker
  
jdk: oraclejdk8

before_install:
  - mysqladmin ping -h127.0.0.1 -P3306
  - sudo service mysql status
  - mysql -u root -p mysql --version

  - sudo apt-get update -qq
  # Remove MySQL. Completely and totally.
  - sudo apt-get remove --purge 'mysql*'
  - sudo apt-get autoremove
  - sudo apt-get autoclean
  - sudo rm -rf /var/lib/mysql
  - sudo truncate -s 0 /var/log/mysql/error.log

  - docker pull mtirsel/mysql-5.1
  - docker run -p 127.0.0.1:3306:3306 --name mysql-51 -e MYSQL_ROOT_PASSWORD= -d mtirsel/mysql-5.1 mysqld --datadir=/var/lib/mysql --user=mysql --server-id=1 --log-bin=/var/lib/mysql/mysql-bin.log --binlog-format=row
  - docker ps -a


  - sudo service mysql status
  - mysql -u root -p mysql --version
  - mysqladmin ping -h127.0.0.1 -P3306

   # Some MySQL debugging (show all the logs).
  - sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ls -lah /var/log
  - sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm cat /var/log/mysql/error.log || true
  - sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm cat /var/log/mysql.err || true

  # Check to make sure we can connect to MySQL via Unix socket.
  - >
    sudo docker exec "$(cat ${container_id})" mysql -u root -proot -e 'show databases;'
    | grep -q 'performance_schema'
    && (echo 'MySQL running normally' && exit 0)
    || (echo 'MySQL not running' && exit 1)
  # Check to make sure we can connect to MySQL via TCP.
  - >
    sudo docker exec "$(cat ${container_id})" mysql -u root -proot -h 127.0.0.1 -e 'show databases;'
    | grep -q 'performance_schema'
    && (echo 'MySQL running normally' && exit 0)
    || (echo 'MySQL not running' && exit 1)


script:
  mvn clean test