language: java

dist: trusty

sudo: required

services:
  - docker
  
jdk: oraclejdk8

before_install:
  - docker pull ruwen/mysql-server-5.1
  - docker run -p 127.0.0.1:3351:3306 --name mysql-51 -e MYSQL_ROOT_PASSWORD=mysql -d ruwen/mysql-server-5.1 mysqld --datadir=/var/lib/mysql --user=root --password=mysql
  - docker ps -a
  - mysql -u root -p mysql --version
  - mysqladmin ping -h127.0.0.1 -P3351

script:
  mvn clean test