language: java

dist: trusty

sudo: required

services:
  - docker
  
jdk: oraclejdk8

before_install:
  - mysql -u root -p mysql --version
  - mysqladmin ping -h127.0.0.1 -P3306

script:
  mvn clean test