language: java

services: docker

services:
  - docker
  - mysql
  
jdk: oraclejdk8

before_install:
  - mysqladmin ping -h127.0.0.1 -P3306
  - sudo service mysql status
  - mysql -u root -p mysql --version

  - sudo apt-get update -qq
  # Remove MySQL. Completely and totally.
  - sudo apt-get remove --purge 'mysql*'
  - sudo apt-get autoremove
  - sudo apt-get autoclean
  - sudo rm -rf /var/lib/mysql
  - sudo truncate -s 0 /var/log/mysql/error.log

  - docker pull mtirsel/mysql-5.1
  - container_id=$(mktemp)
  - 'docker run -p 127.0.0.1:3306:3306 --name mysql-51 -e MYSQL_ROOT_PASSWORD=mysql -d mtirsel/mysql-5.1 mysqld --datadir=/var/lib/mysql --user=mysql --server-id=1 --log-bin=/var/lib/mysql/mysql-bin.log --binlog-format=row > "${container_id}"'
  - docker ps -a
  - docker exec -i mysql-51 mysql -uroot -pmysql --version
  - sudo docker exec "$(cat ${container_id})" mysql -uroot -pmysql -h 127.0.0.1 -e 'show databases;'
  #- sudo service mysql status
  #- mysqladmin ping -h127.0.0.1 -P3306
  #- mysql -u root -P 3306 -h 127.0.0.1 --version


   # Some MySQL debugging (show all the logs).
  - docker exec -i mysql-51 ls -lah /var/log
  #- docker exec -i mysql-51 cat /var/log/mysql/error.log || true
  #- docker exec -i mysql-51 cat /var/log/mysql.err || true
  - docker exec -i mysql-51 mysql -uroot -pmysql -h 127.0.0.1 <<< "select now();"
  - echo "select now();" > dump.sql
  - docker exec -i mysql-51 mysql -uroot -pmysql -h 127.0.0.1 < dump.sql
  - docker exec -i mysql-51 mysql -uroot -pmysql -h 127.0.0.1 -e 'show databases;'
  - docker exec -i mysql-51 mysql -uroot -pmysql -e 'show databases;' 


  # Check to make sure we can connect to MySQL via Unix socket.
  - >
    docker exec -i mysql-51 mysql -u root -pmysql -e 'show databases;' | grep -q 'information_schema' && (echo 'MySQL running normally' && exit 0) || (echo 'MySQL not running' && exit 1)
  # Check to make sure we can connect to MySQL via TCP.
  - >
    sudo docker exec "$(cat ${container_id})" mysql -u root -proot -h 127.0.0.1 -e 'show databases;' | grep -q 'information_schema' && (echo 'MySQL running normally' && exit 0) || (echo 'MySQL not running' && exit 1)

script:
  mvn clean test