language: java

sudo: required

dist: trusty

services:
  - docker
  - mysql
  
jdk: oraclejdk8

before_install:
  - docker pull mtirsel/mysql-5.1
  - docker run -p 127.0.0.1:3351:3306 --name mysql-51 -e MYSQL_ROOT_PASSWORD=mysql -d mtirsel/mysql-5.1 mysqld --datadir=/var/lib/mysql --user=mysql --server-id=1 --log-bin=/var/lib/mysql/mysql-bin.log --binlog-format=row
  - docker ps -a

script:
  - ./test.sh