language: java


services:
  - docker
  - mysql
  
jdk: oraclejdk8

before_install:
  - mysqladmin ping -h127.0.0.1 -P3306
  - sudo service mysql status
  - mysql -u root -p mysql --version

  - sudo apt-get update -qq
  # Remove MySQL. Completely and totally.
  - sudo apt-get remove --purge 'mysql*'
  - sudo apt-get autoremove
  - sudo apt-get autoclean
  - sudo rm -rf /var/lib/mysql
  - sudo truncate -s 0 /var/log/mysql/error.log

  - docker pull mtirsel/mysql-5.1
  - docker run -p 127.0.0.1:3306:3306 --name mysql-51 -e MYSQL_ROOT_PASSWORD= -d mtirsel/mysql-5.1 mysqld
  - docker ps -a


  #- sudo service mysql status
  #- mysqladmin ping -h127.0.0.1 -P3306
  #- mysql -u root -P 3306 -h 127.0.0.1 --version


   # Some MySQL debugging (show all the logs).
  - docker exec -i mysql-51 mysql -uroot --version
  - docker exec -i mysql-51 mysql -uroot <<< "select database();select now();"
  - docker exec -i mysql-51 mysql -uroot < dump.sql
  - docker exec -i mysql-51 ls -lah /var/log
  - docker exec -i mysql-51 cat /var/log/mysql/error.log || true
  - docker exec -i mysql-51 cat /var/log/mysql.err || true

  # Check to make sure we can connect to MySQL via Unix socket.
  - >
    docker exec -i mysql-51 mysql -u root -e 'show databases;' | grep -q 'performance_schema' && (echo 'MySQL running normally' && exit 0)
    || (echo 'MySQL not running' && exit 1)
  # Check to make sure we can connect to MySQL via TCP.
  - >
    sudo docker exec "$(cat ${container_id})" mysql -u root -proot -h 127.0.0.1 -e 'show databases;' | grep -q 'performance_schema' && (echo 'MySQL running normally' && exit 0)
    || (echo 'MySQL not running' && exit 1)

script:
  mvn clean test