language: java


services:
  - docker
  
jdk: oraclejdk8

before_install:
  - mysqladmin ping -h127.0.0.1 -P3306
  - sudo service mysql status
  - mysql -u root -p mysql --version

  - sudo apt-get update -qq
  # Remove MySQL. Completely and totally.
  - sudo apt-get remove --purge 'mysql*'
  - sudo apt-get autoremove
  - sudo apt-get autoclean
  - sudo rm -rf /var/lib/mysql
  - sudo truncate -s 0 /var/log/mysql/error.log

  - docker pull ruwen/mysql-server-5.1
  - docker run -p 127.0.0.1:3306:3306 --name mysql-51 -e MYSQL_ROOT_PASSWORD=mysql -d ruwen/mysql-server-5.1 mysqld --datadir=/var/lib/mysql --user=root --password=mysql
  - docker ps -a

  - sudo service mysql status
  - mysql -u root -p mysql --version
  - mysqladmin ping -h127.0.0.1 -P3306

script:
  mvn clean test