/**
 * 
 */
package fr.argus.socle.util;

/**
 * @author mamadou.dansoko
 *
 */
public enum Signalements {
	 PRESSE_ERREUR_DEFAUT											("201"),
	 RESSE_FICHIER_ABSENT_IN										("202"),
	 PRESSE_FICHIER_ABSENT_OUT										("203"),
	 PRESSE_REPERTOIRE_ABSENT_IN									("204"),
	 PRESSE_REPERTOIRE_ABSENT_OUT									("205"),
	 PRESSE_NUMERO_PUBLICATION_ABSENT								("206"),
	 PRESSE_NUMERO_PUBLICATION_INCORRECT							("207"),
	 PRESSE_SCRIPT_ABSENT											("208"),
	 PRESSE_SCRIPT_ERREUR_COMPILATION								("209"),
	 AUTO_TEST_EN_ERREUR_CONTENU 									("210"),
	 AUTO_TEST_EN_ERREUR_TEMPS										("211"),
	 AUTO_TEST_OK													("212"),
	 PRESSE_ALERTE_GENERALE											("250"),
	 PRESSE_LOG_DEFAUT												("300"),
	 PRESSE_REMISE_EN_ATTENTE										("301"),
	 PF_TELECHARGEMENT_OK_											("500"),
	 PF_TELECHARGEMENT_EN_COURS_									("510"),
	 PF_TELECHARGEMENT_ERREUR_SITE_NON_TROUVE						("520"),
	 PF_TELECHARGEMENT_ERREUR_LOGIN_INCORRECT						("530"),
	 PF_TELECHARGEMENT_ERREUR_TRANSFERT_INTERROMPU					("540"),
	 PF_TELECHARGEMENT_ERREUR_REPERTOIRE_INTROUVABLE				("550"),
	 PF_TELECHARGEMENT_ERREUR_BASE_DE_DONNEES						("551"),
	 PF_TELECHARGEMENT_ERREUR_TEMPS_DEPASSE             			("552"),
	 PF_IMPORT_PIVOT_OK_ 											("600"),
	 PF_IMPORT_PIVOT_EN_COURS_ 										("601"),
	 PF_IMPORT_PIVOT_ERREUR_ARCHIVE_CORROMPUE 						("602"),
	 PF_IMPORT_PIVOT_ERREUR_REPERTOIRE_INTROUVABLE			 		("603"),
	 PF_IMPORT_PIVOT_ERREUR_BASE_DE_DONNEES 						("604"),
	 PF_IMPORT_PIVOT_ERREUR_TEMPS_DEPASSE 							("605"),
	 PF_IMPORT_PIVOT_ERREUR_COPIE_FICHIER                           ("606"),
	 PF_DEDOUBLONNEMENT_OK_ 										("610"),
	 PF_DEDOUBLONNEMENT_EN_COURS_ 									("620"),
	 PF_DEDOUBLONNEMENT_ERREUR_BASE_DE_DONNEES						("630"),
	 PF_DEDOUBLONNEMENT_ERREUR_TEMPS_DEPASSE						("640"),
	 PF_DEDOUBLONNEMENT_ERREUR_FORMAT_INVALIDE						("650"),
	 PF_DEDOUBLONNEMENT_ERREUR_RESOURCE_INTROUVABLE                 ("651"),
	 PF_SOUS_LOTS_OK_												("660"),
	 PF_SOUS_LOTS_EN_COURS_											("670"),
	 PF_SOUS_LOTS_ERREUR_BASE_DE_DONNEES							("680"),
	 PF_SOUS_LOTS_ERREUR_TEMPS_DEPASSE								("690"),
	 PF_SOUS_LOTS_ERREUR_FORMAT_INVALIDE							("700"),
	 PF_SOUS_LOTS_TERMINE_TOTALEMENT_DOUBLE							("705"),
	 PF_SOUS_LOTS_ATTENTE_TRAITEMENT_AUTRE_INSTANCE					("706"),
	 PF_COUVERTURE_OK_												("710"),
	 PF_COUVERTURE_EN_COURS_										("720"),
	 PF_COUVERTURE_ERREUR_BASE_DE_DONNEES							("730"),
	 PF_COUVERTURE_ERREUR_TEMPS_DEPASSE								("740"),
	 PF_COUVERTURE_ERREUR_FORMAT_INVALIDE							("750"),
	 PF_IDENTIFICATION_OK_					            			("820"),
	 PF_IDENTIFICATION_EN_COURS_									("830"),
	 PF_IDENTIFICATION_ERREUR_FORMAT_INVALIDE						("840"),
	 PF_IDENTIFICATION_ERREUR_BASE_DE_DONNEES						("850"),
	 PF_IDENTIFICATION_ERREUR_TEMPS_DEPASSE							("860"),
	 PF_IDENTIFICATION_ERREUR_REPERTOIRE_INTROUVABLE 				("870"),	
	 PF_POINTAGE_OK_ 												("880"),
	 PF_POINTAGE_EN_COURS_ 											("890"),
	 PF_POINTAGE_ERREUR_BASE_DE_DONNEES 							("900"),
	 PF_POINTAGE_ERREUR_FORMAT_INVALIDE 							("910"),
	 PF_POINTAGE_ERREUR_REPERTOIRE_INTROUVABLE 						("920"),
	 PF_POINTAGE_ERREUR_TEMPS_DEPASSE								("930"),
	 PF_POINTAGE_ERREUR_WEBSERVICE									("940"),
	 PF_CREATION_LIVRABLE_OK_										("950"),
	 PF_CREATION_LIVRABLE_EN_COURS_									("960"),
	 PF_CREATION_LIVRABLE_ERREUR_BASE_DE_DONNEES					("970"),
	 PF_CREATION_LIVRABLE_ERREUR_TEMPS_DEPASSE						("980"),
	 PF_CREATION_LIVRABLE_ERREUR_FORMAT_INVALIDE					("990"),
	 PF_CREATION_LIVRABLE_ERREUR_REPERTOIRE_SOURCE_INTROUVABLE 		("1000"),
	 PF_CREATION_LIVRABLE_ERREUR_REPERTOIRE_DESTINATION_INTROUVABLE ("1010"),
	
	
	 PF_FEUILLE_POINTAGE_OK_ 										("760"),
	 PF_FEUILLE_POINTAGE_EN_COURS_ 									("765"),
	 PF_FEUILLE_POINTAGE_ERREUR_BASE_DE_DONNEES 					("770"),
	 PF_FEUILLE_POINTAGE_ERREUR_FORMAT_INVALIDE 					("775"),
	 PF_FEUILLE_POINTAGE_ERREUR_REPERTOIRE_INTROUVABLE 				("780"),
	 PF_FEUILLE_POINTAGE_ERREUR_TEMPS_DEPASSE						("785"),
	 PF_ATTRIBUT_ENCOURS                                            ("790"),
	 PF_ATTRIBUT_OK                                                 ("795"),
	 PF_ATTRIBUT_ERREUR_BASE_DE_DONNEES                             ("800"),	
	 PF_FICHIER_IMAGE_POSTION_ENCOURS         						("871"),
	 PF_FICHIER_IMAGE_POSTION_OK         						    ("872"),
	 PF_FICHIER_IMAGE_POSTION_ERREUR_BASE_DE_DONNEES				("873"),
	 PF_FICHIER_IMAGE_POSTION_ERREUR_REPERTOIRE_SOURCE_INTROUVABLE 		("874"),
	 PF_FICHIER_IMAGE_POSTION_ERREUR_REPERTOIRE_DESTINATION_INTROUVABLE ("875"),
	 PF_FICHIER_IMAGE_POSTION_ERREUR_ARCHIVE_CORROMPUE 					("876"),
	 PF_ERREUR_FERMETURE_ARCHIVE			 	                        ("877"),
	 PF_MODALITE_APPRO_ERREUR_NON_DEFINIE                               ("251"),
	 PF_ERREUR_GENERATION_PIVOT                                     ("252"),
	 PF_ERREUR_EXECUTION_XSL                                        ("253"),
	 PF_CONTENU_PIVOT_DOUBLON                                       ("607"),
	 PF_CONTENU_PIVOT_ORUGINAL                                      ("608");
	
	
	
	private String code;
	private Signalements(String code){
		this.code = code;
	}
	
	public String getCode() {
		return code;
	}		
}
